vim.keymap.set('t', '<Esc>',  [[<C-\><C-n>]], { desc = "Exit terminal-mode" })
vim.keymap.set('t', '<A-h>',  [[<C-\><C-N><C-w>h]], { desc = "ALT+{h,j,k,l} window navigation" })
vim.keymap.set('t', '<A-j>',  [[<C-\><C-N><C-w>j]], { desc = "ALT+{h,j,k,l} window navigation" })
vim.keymap.set('t', '<A-k>',  [[<C-\><C-N><C-w>k]], { desc = "ALT+{h,j,k,l} window navigation" })
vim.keymap.set('t', '<A-l>',  [[<C-\><C-N><C-w>l]], { desc = "ALT+{h,j,k,l} window navigation" })

vim.keymap.set('i', '<A-h>',  [[<C-\><C-N><C-w>h]], { desc = "ALT+{h,j,k,l} window navigation" })
vim.keymap.set('i', '<A-j>',  [[<C-\><C-N><C-w>j]], { desc = "ALT+{h,j,k,l} window navigation" })
vim.keymap.set('i', '<A-k>',  [[<C-\><C-N><C-w>k]], { desc = "ALT+{h,j,k,l} window navigation" })
vim.keymap.set('i', '<A-l>',  [[<C-\><C-N><C-w>l]], { desc = "ALT+{h,j,k,l} window navigation" })

vim.keymap.set('n', '<A-h>',  [[<C-\><C-N><C-w>h]], { desc = "ALT+{h,j,k,l} window navigation" })
vim.keymap.set('n', '<A-j>',  [[<C-\><C-N><C-w>j]], { desc = "ALT+{h,j,k,l} window navigation" })
vim.keymap.set('n', '<A-k>',  [[<C-\><C-N><C-w>k]], { desc = "ALT+{h,j,k,l} window navigation" })
vim.keymap.set('n', '<A-l>',  [[<C-\><C-N><C-w>l]], { desc = "ALT+{h,j,k,l} window navigation" })
