#!/bin/bash

# Log output:
#
# * 51c333e    (12 days)    <Gary Bernhardt>   add vim-eunuch
#

HASH="%C(yellow)%h%Creset"
RELATIVE_TIME="%Cgreen(%ar)%Creset"
AUTHOR="%C(bold blue)<%an>%Creset"
REFS="%C(red)%d%Creset"
SUBJECT="%s"

FORMAT="$HASH $REFS $RELATIVE_TIME $AUTHOR $SUBJECT"

show_git_head() {
    pretty_git_log -1
    git show -p --pretty="tformat:${FORMAT}"
}

pretty_git_log() {
    git log --decorate --graph --abbrev-commit --date=relative --pretty="tformat:${FORMAT}" $* 
}

