alias spec='rspec -f d --color'
alias gmutt='mutt -F ~/.muttrc'
alias wmutt='mutt -F ~/.muttrc_work'
alias g='git'
alias test_env='export CUCUMBER_SUFFIX=_cucumber && export RAILS_ENV="test" && export RACK_ENV="test"'
